baseURL: https://gircore.tiede.org/
title: Gir.Core
theme: book

languageCode: en-us
uglyURLs: true

contentDir: ../content
publishDir: ../output
themesDir: ../themes

params:
  BookTheme: "auto"
  BookLogo: "logo.png"